global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.

scrape_configs:
  - job_name: 'flask_application'
    static_configs:
      - targets: ['ec2-18-217-56-84.us-east-2.compute.amazonaws.com']
